import {
  boolean,
  doublePrecision,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

export const bookingsSchema = pgTable("bookings", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull(),
  userName: text("user_name").notNull().default(""),
  userEmail: text("user_email"),
  petId: uuid("pet_id").notNull(),
  petName: text("pet_name").notNull(),
  petBreed: text("pet_breed").default(""),
  petAge: integer("pet_age").default(0),
  serviceName: text("service_name").notNull(),
  servicesJson: text("services_json"),
  attendancePhotos: text("attendance_photos"),
  establishmentId: uuid("establishment_id"),
  establishmentName: text("establishment_name").notNull().default(""),
  establishmentAddress: text("establishment_address").default(""),
  driverId: uuid("driver_id"),
  driverName: text("driver_name"),
  driverPhotoUrl: text("driver_photo_url"),
  transportStatus: text("transport_status").notNull().default("NONE"),
  vetId: uuid("vet_id"),
  vetName: text("vet_name"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }).notNull(),
  price: doublePrecision("price").notNull().default(0),
  priceVariable: boolean("price_variable").notNull().default(false),
  status: text("status").notNull().default("PENDENTE"),
  paymentStatus: text("payment_status").notNull().default("NONE"),
  paymentMethod: text("payment_method"),
  reminderSentAt: timestamp("reminder_sent_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});
